### ISSUE TITLE
You removed real_file_name from PutObjectRequest

### ISSUE THREAD

**Issue by thattommyhall** [SpectraLogic/ds3_python_sdk#96]
In 87b0ce4880d2e9c7e9e9f356cee2322b09f9dbac you remove the real_file_name param, but you use it in both your documentation and examples (see [here](https://github.com/SpectraLogic/ds3_python_sdk/search?utf8=%E2%9C%93&q=real_file_name)) 

This broke some code I wrote for a customer of yours

**Comment by rpmoore** [comment]
We will update our examples to reflect the change that was made.  We had identified an error in the SDK that could only be fixed by pulling the file handing logic out of the SDK and into the client code.  For an explanation as to why the change was made, please refer to this google group post on the topic: https://groups.google.com/forum/#!topic/spectralogicds3-sdks/nNuPCkkwJAU

**Comment by rpmoore** [comment]
The samples have been updated to reflect the latest API changes.  Let us know if you need anything else or would like to see specific examples.
